[package]
name = "dusts"
version = "0.1.0"
edition = "2024"
authors = ["bubb1es71 <bubb1es71@proton.me>"]
license = "MIT"

[dependencies]
bitcoin = "0.32.5"
clap = { version = "4", features = ["derive", "env"] }
